const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/v1/auth", require("./routes/auth.routes"));
app.use("/api/v1/tools", require("./routes/tools.routes"));
app.use("/api/v1/bookings", require("./routes/bookings.routes"));
app.use("/api/v1/payments", require("./routes/payments.routes"));
app.use("/api/v1/admin", require("./routes/admin.routes"));
module.exports = app;
